### ISSUE TITLE
Payments Initial Setup Automation

### ISSUE THREAD

**Issue by Keyrxng** [Keyrxng/didactic-octo-train#35]
The current manual steps are in the initial setup. It would be great to automate:

Iteration 1 - Currently (Manual)
Deposit ETH into the bot signing key's wallet address.
Call approve on payment token contract address for Permit2 spender from this new wallet.
I wish we could use a relayer to handle 2. That way it would be very clean from a new partner setup perspective. All they would need to do is deposit the spending token (e.g. DAI) in the new wallet, and then generate a signature to authorize the approve call and pass it along to a relayer.

Iteration 2 - Next (Automated)
Bot generates a private key
Bot updates the repository secret with its private key
Bot requests for a top-up of the wallet in DAI or whatever
After the bot is topped up, it gets a relayer to call approve on DAI for permit2 spender
Bot is initialized.

**Comment by KxyChain** [comment]
A couple of clarifications.

Is a new Private Key being generated only once? Or is a new one generated for each issue or bounty hunter?

How is the top-up request being presented? Is it generating a transaction to be signed or is it more of a message to an admin?

DAI doesn't contain an allow function, are you referring to the permit pattern which is signature based?
Who or what are the relayer and permit2?

**Comment by Keyrxng** [comment]
Is a new Private Key being generated only once? Or is a new one generated for each issue or bounty hunter?

The current vision is to have a new private key generated PER instance of the bounty-bot. So only a one time setup per partner.

How is the top-up request being presented? Is it generating a transaction to be signed or is it more of a message to an admin?

In the future vision I anticipate we'll be using Gnosis Multisigs. The bot can have an individual signing key and queue a top-up transaction. Code maintainers can get push notifications conveniently for this on the Safe iOS app (not sure if they have an android app, but I use the iOS app all the time, and its great.)

DAI doesn't contain an allow function, are you referring to the permit pattern which is signature based?

Sorry! I meant approve

Who or what are the relayer and permit2?

We're currently using Permit2 which is a separate contract created by the Uniswap team. More information on that is available here https://dao.ubq.fi/ubiquibot-setup.

**Comment by KxyChain** [comment]
/ask can you provide a minimal example of a working automated flow?
