### ISSUE TITLE
Testing Previous

### ISSUE THREAD

**Issue by Keyrxng** [Keyrxng/didactic-octo-train#36]
Resolves #35

**Comment by Keyrxng** [comment]
/ask consider the context and think of an alternative automated solution

**Comment by KxyChain** [comment]
I think this new approach is solid but have we considered the security implications of this?

**Comment by Keyrxng** [comment]
/ask KxyChain makes a good point, what do you think?

**Comment by Keyrxng** [comment]
/ask KxyChain makes a good point, what do you think?

**Comment by Keyrxng** [comment]
/ask KxyChain makes a good point, what do you think?

**Comment by Keyrxng** [comment]
/ask what is the token size of this input?
